version: "2"

services:
  signaler:
    build: ./signaler
    ports:
      - "5001:443"
    volumes:
     - ./signaler:/usr/local/src/github.com/pions/demo-conference/signaler

  turn:
    image: zolochevska/turn-server
    restart: always
    ports:
      - 3478:3478
      - 3478:3478/udp
    command: username password countable.ca

  www:
    build: ./www
    ports:
      - "443:443"
    volumes:
     - ./www:/usr/local/src/github.com/pions/demo-conference/www
